Description: Create a VPC with a SG which references itself
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  sgtester:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: vpc tester sg
      VpcId: vpc-0e3384da61ec95b4f
